models:
  - name: fact_orders
    description: "Fact model of total number of distinct orders and distinct customers per year"
    columns:
      - name: order_purchase_year
        description: "Year extracted from order_purchase_date" 
        tests:
          - not_null:
              config:
                severity: warn

      - name: order_status
        description: "Current status of the order" 
        tests:
          - not_null:
              config:
                severity: warn

      - name: cnt_distinct_order
        description: "Number of distinct orders in a given year" 
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
              config:
                severity: warn

      - name: cnt_distinct_customer
        description: "Number or distinct customers in a given year"
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
              config:
                severity: warn

  - name: fact_orders_geography
    description: "Fact model combining order and customer geography details"
    columns:
      - name: order_purchase_year
        description: "Year extracted from order_purchase_timestamp"
        tests:
          - not_null:
              config:
                severity: warn

      - name: order_status
        description: "Current status of the order"
        tests:
          - not_null:
              config:
                severity: warn

      - name: customer_city
        description: "Customer's city"
        tests:
          - not_null:
              config:
                severity: warn

      - name: customer_state
        description: "Customer's state"
        tests:
          - not_null:
              config:
                severity: warn

      - name: cnt_distinct_order
        description: "Number of distinct orders in a given year, in a given state/city" 
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
              config:
                severity: warn

      - name: cnt_distinct_customer
        description: "Number or distinct customers in a given year, in a given state/city"
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
              config:
                severity: warn

  - name: fact_seller_performance
    description: "Fact model aggregating sales performance metrics per seller"
    columns:
      - name: seller_id
        description: "Seller's unique identifier"
        tests:
          - not_null:
              config:
                severity: warn
          - unique:
              config:
                severity: warn

      - name: total_sales_value
        description: "Sum of total sales attributed to a given seller_id"
        tests:
          - not_null:
              config:
                severity: warn
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
              config:
                severity: warn

      - name: order_count
        description: "Number of distinct sales attributed to a given seller_id"
        tests:
          - not_null:
              config:
                severity: warn
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
              config:
                severity: warn
  
  - name: fact_product_performance
    description: "Fact model aggregating product and delivery metrics per category"
    columns:
      - name: category
        description: "Product category" 
        tests:
          - unique:
              config:
                severity: warn
                
          - not_null:
              config:
                severity: warn

      - name: total_revenue
        description: "Total sales (price + freight_value) for a given category"
        tests:
          - not_null:
              config:
                severity: warn

      - name: cnt_distinct_products_sold
        description: "Number of unique products sold within a given category"
        tests:
          - not_null:
              config:
                severity: warn

      - name: cnt_distinct_order
        description: "Number of unique orders placed within a given category"
        tests:
          - not_null:
              config:
                severity: warn

      - name: avg_delivery_days
        description: "Average delivery days for a given category"
        tests:
          - not_null:
              config:
                severity: warn

      - name: avg_product_weight_g
        description: "Average product weight in grams within a given category"
        tests:
          - not_null:
              config:
                severity: warn

      - name: avg_product_photos_qty
        description: "Average number of photos per product withing a given category"
        tests:
          - not_null:
              config:
                severity: warn
                